include:
  - docker-compose.db.yml
  - docker-compose.bus.yml

services:
  sidecar:
    build:
      context: dockerfiles/sidecar
      dockerfile: Dockerfile
    tty: true
    image: sidecar:latest
    container_name: sidecar
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - golang_deps:/root/go
      - ../:/development
    working_dir: /development
    networks:
      - default
    ports:
      - "8080:8080"

networks:
  default:

volumes:
  golang_deps: